{"name": "test_login_username_error", "status": "passed", "attachments": [{"name": "stdout", "source": "69153459-2c8e-4fff-b055-adb175e3b2e8-attachment.txt", "type": "text/plain"}], "start": 1709085399709, "stop": 1709085399724, "uuid": "cfd4f268-3935-43ae-b235-db99d9b13f54", "historyId": "1047ca01db95e034c24b7b9b866137fb", "testCaseId": "7d6844bc50864e700b98ea2a6270409d", "fullName": "post1.Testlogin#test_login_username_error", "labels": [{"name": "feature", "value": "用户登录"}, {"name": "story", "value": "用户名错误，登录失败"}, {"name": "suite", "value": "post1"}, {"name": "subSuite", "value": "Testlogin"}, {"name": "host", "value": "WIN-Q4LBVBF2PED"}, {"name": "thread", "value": "5800-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "post1"}]}